/** Auto-generated Typecast EN→KO voice names (from Typecast docs). */
export const TYPECAST_VOICE_NAME_KO: Record<string, string> = {
  "Aaron": "에런",
  "Inhye": "인혜",
  "Piljae": "필재",
  "Abigail": "아비게일",
  "Inseong": "인성",
  "Pyeonghwa": "평화",
  "Ae-ran": "애란",
  "Instructor Han": "한유격 교관",
  "Rachel": "레이첼",
  "Ael": "아엘",
  "Insun": "인선",
  "Ravi": "라비",
  "Agatha": "아가사",
  "Jabbaba": "자바바",
  "Rayeon": "라연",
  "Aiden": "에이든",
  "Jack": "잭",
  "Rebecca": "레베카",
  "Alena": "알레나",
  "Jack-o’-Lantern": "잭오랜턴",
  "Reporter Bona": "다보나 기자",
  "Alex": "알렉스",
  "Jackson": "잭슨",
  "Reporter Catalina": "카탈리나 기자",
  "Amber": "엠버",
  "Jaeho": "재호",
  "Reporter Jinsub": "송진섭 기자",
  "Anchor Hwa": "김경화 앵커",
  "Jaehun": "재훈",
  "Reporter Kang": "강수정 기자",
  "Angela": "안젤라",
  "Jaejun": "재준",
  "Reporter Lee": "이승주 기자",
  "Anja": "안냐",
  "Jaekyung": "재경",
  "Reporter Parkchan": "박찬 기자",
  "Annabelle the Ghost": "귀신 애나벨",
  "Jaesun": "재선",
  "Rex": "렉스",
  "Annie": "애니",
  "JaeYi": "재이",
  "Riley": "라일리",
  "April": "에이프릴",
  "Jaeyoung": "재영",
  "Risan Ji": "지리산",
  "Arang": "아랑",
  "Jain": "자인",
  "Rita": "리타",
  "Ari": "아리",
  "Jake": "제이크",
  "River": "리버",
  "Arin": "아린",
  "Janet": "재닛",
  "Robert": "로버트",
  "Athena": "아테나",
  "Jangho": "장호",
  "Robo": "로보",
  "Audrey": "오드리",
  "Jangwoon": "장운",
  "Romi": "로미",
  "Avery": "에이버리",
  "Jechan": "제찬",
  "Ron": "론",
  "Avong": "아봉",
  "Jeff": "제프",
  "Roro": "로로",
  "Azzi": "아찌",
  "Jenna": "제나",
  "Rowoon": "로운",
  "Babilon": "바빌론",
  "Jennifer": "제니퍼",
  "Royce": "로이스",
  "Bell": "벨",
  "Jeong Choi": "최정",
  "Rudolph": "루돌프",
  "Ben": "벤",
  "Jeongah": "정아",
  "Ruri": "루리",
  "Benny": "베니",
  "JeongJin": "정진",
  "Rusty": "러스티",
  "Beri": "베리",
  "Jeongseob": "정섭",
  "Ryan": "라이언",
  "Billie": "빌리",
  "Jerome": "제롬",
  "Ryueun": "류은",
  "Bomi": "이보미",
  "Jewby": "쥬비",
  "Sabrina the Witch": "마녀 사브리나",
  "Bonggyu": "봉규",
  "Jian": "지안",
  "Saeron": "새론",
  "Bongman Kim": "김봉만",
  "Jicheol": "지철",
  "Salty Chan-gu": "삐뚤어진 찬구",
  "Bono": "보노",
  "Jihee": "지희",
  "Samantha": "사만다",
  "Bora": "보라",
  "Jihoon": "지훈",
  "Sammy": "새미",
  "Brad": "브래드",
  "Jihyun": "지현",
  "Sangdo": "상도",
  "Bruce": "브루스",
  "Jimmy": "지미",
  "Sanghoon": "상훈",
  "Buddy": "버디",
  "Jin": "진",
  "Sangwoo": "상우",
  "Bumsoo": "범수",
  "Jinhan": "진한",
  "Santa": "산타",
  "Buttaguy": "빠다가이",
  "Jinhang Kim": "김진행",
  "Santa Claus": "산타클로스",
  "Caitlyn": "케이틀린",
  "Jinhee": "진희",
  "Santa Reporter": "VJ 싼타",
  "Callan": "칼란",
  "Jinhyuk": "진혁",
  "Sara": "세라",
  "Camila": "카밀라",
  "Jinseo": "진서",
  "Sean": "션",
  "Captain Bill": "캡틴 빌",
  "Jinung": "진웅",
  "SeHee": "세희",
  "Carl": "칼",
  "Jinwoo": "진우",
  "Seheon": "세헌",
  "Carlos": "카를로스",
  "Jiwoo": "지우",
  "Sejin": "세진",
  "Carol": "캐롤",
  "Jiyoon": "지윤",
  "Sena": "세나",
  "Catherine": "캐서린",
  "Jiyoung": "지영",
  "Seohee": "서희",
  "Chad": "채드",
  "Jodie": "조디",
  "Seojin": "서진",
  "Chaeah": "채아",
  "Jolly": "졸리",
  "Seojoon": "서준",
  "Chan-gu": "찬구",
  "Jongdae": "종대",
  "Seok Choi": "최석",
  "Changbae": "창배",
  "Jooeun": "주은",
  "SeokPil": "한석필",
  "Changhee": "창희",
  "Joonghyun": "중현",
  "Seokpyo": "석표",
  "Changmin": "창민",
  "Joongsik": "중식",
  "Seolhwa": "설화",
  "Changsu": "박창수",
  "Joonkyu": "준규",
  "Seonha": "선하",
  "Chanhyuk": "찬혁",
  "Joshua": "조슈아",
  "Seoyeon": "서연",
  "Charlotte": "샬롯",
  "Juha": "주하",
  "Seoyoon": "서윤",
  "Chase": "체이스",
  "Juho": "주호",
  "Seungah": "승아",
  "Cheolhoon": "철훈",
  "Jungbong": "정봉",
  "Seungheon": "승헌",
  "Cheolyong": "리철용",
  "Junghee": "정희",
  "Seungho": "승호",
  "Cherry": "체리",
  "Jungjae": "정재",
  "Seunghwa": "승화",
  "Chester": "체스터",
  "Jungmin": "정민",
  "Seungjae": "승재",
  "Chiho": "치호",
  "Jungseok": "정석",
  "Seungmoon": "승문",
  "Chloe": "클로이",
  "Jungsoon": "정순",
  "Seungwon": "승원",
  "Choyeon": "강초연 교관",
  "Jungwon": "정원",
  "Seungyeon": "승연",
  "Chungah": "청아",
  "Junhee": "준희",
  "Sewoo": "세우",
  "Chunsik Kang": "강춘식 기자",
  "Junho": "준호",
  "Shana": "샤나",
  "Claire": "클레어",
  "JunKi": "준기",
  "Sheriff Kim": "김반장",
  "Classic Narrator": "미스타 변사",
  "Junsang": "준상",
  "Shinhe": "신혜",
  "Cole": "콜",
  "Junseong": "준성",
  "Shinwook": "신욱",
  "Cox": "콕스",
  "Justice Roh": "정의로",
  "Shotgun": "샷건",
  "Cyrus": "사이러스",
  "Justin": "저스틴",
  "Simon": "사이먼",
  "Dabin": "다빈",
  "Juwon": "주원",
  "Sindarin": "신다린",
  "Daegil": "대길",
  "Juyoung": "주영",
  "Sio": "시오",
  "Dahee": "다희",
  "K-Santa": "산타 할아버지",
  "Siwon": "시원",
  "Dahyeon": "다현",
  "Kangil": "강일",
  "Siwoo": "시우",
  "Damian": "데이미언",
  "Kanno": "칸노",
  "Siyeon": "시연",
  "Dan": "댄",
  "Katie": "케이티",
  "Skylar": "스카일러",
  "Dana": "다나",
  "Kelly": "켈리",
  "Slushy": "슬러시",
  "Dasom": "다솜",
  "Kelsey": "켈시",
  "Smoke": "스모크",
  "David": "데이비드",
  "Kevin": "케빈",
  "Sohye": "소혜",
  "Dean": "딘",
  "Keybo": "키보",
  "Sojin": "소진",
  "Deokhwan": "덕환",
  "Kijang Kim": "김기장",
  "Soobin": "수빈",
  "Dohan": "도한",
  "Killian the Vampire": "뱀파이어 킬리언",
  "Sookhee": "숙희",
  "Dohee": "도희",
  "Kiseob": "기섭",
  "Sooni": "순이",
  "Dohyun": "도현",
  "Klip Kim": "클립 킴",
  "Sophia": "소피아",
  "Dollar Jr.": "달러 주니어",
  "Koombo": "쿰보",
  "Sora": "소라",
  "Doug": "더그",
  "Kristen": "크리스틴",
  "Soye": "소예",
  "Doughnut": "도넛",
  "Kukhee": "국희",
  "Soyi": "소이",
  "DU5T": "더스트",
  "Kwonil": "권일",
  "Soyoung": "소영",
  "Duckchun": "덕춘",
  "Kyumin": "규민",
  "Soyul": "소율",
  "Duke": "듀크",
  "Kyungho": "경호",
  "Spice": "스파이스",
  "Dukgu": "덕구",
  "Kyungsoo": "경수",
  "Sportscaster Kang": "강수정 캐스터",
  "Duman": "두만",
  "Kyungsook": "경숙",
  "Sportscaster Tony": "이영광 캐스터",
  "Dupil": "곽두필",
  "Lady Cho": "단희빈",
  "Starling": "스탈링",
  "DVZY": "데이지",
  "Lala": "라라",
  "Stephanie": "스테파니",
  "Dylan": "딜런",
  "Lamie": "라미",
  "Storyteller Jinsub": "송진섭 스토리텔러",
  "E-seller Sherri": "쇼린이",
  "Landon": "랜던",
  "Sua": "수아",
  "Echo": "에코",
  "Larry": "래리",
  "Suho": "수호",
  "Edward": "에드워드",
  "Leo": "레오",
  "Suji": "수지",
  "Elias": "엘리아스",
  "Liam": "리암",
  "Sujin": "수진",
  "Elise": "엘리스",
  "Lindsay": "린지",
  "Sullock Hong": "홍설록",
  "Ella": "엘라",
  "Liz": "리즈",
  "Sumin": "수민",
  "Eman": "이만",
  "Lloyd": "로이드",
  "Sungbae": "성배",
  "Emma": "엠마",
  "Logan": "로건",
  "Sunggyu": "성규",
  "Eunbin": "은빈",
  "Lucille": "루실",
  "Sungho": "성호",
  "Eunchae": "은채",
  "Luna": "루나",
  "Sunghoon": "성훈",
  "Eunha": "은하",
  "Lydia": "리디아",
  "Sunghyun": "성현",
  "Eunsol": "은솔",
  "Maddie": "매디",
  "Sungjun": "홈쇼핑 성준",
  "Frankenstein": "프랑켄슈타인",
  "Maisie": "메이시",
  "Sungkwon": "성권",
  "Furnando": "터르난도",
  "Margaret": "마가렛",
  "Sungtae": "성태",
  "Gaeul": "가을",
  "Margot": "마고",
  "Sungwook": "성욱",
  "Gahee": "가희",
  "Matthew": "매튜",
  "Sunyoung": "선영",
  "George": "조지",
  "MBTI EF (F)": "MBTI EF 여",
  "Suyoon": "수윤",
  "GeumHee": "금희",
  "MBTI EF (M)": "MBTI EF 남",
  "Sylvia": "실비아",
  "Geunhyeok": "근혁",
  "MBTI ET (F)": "MBTI ET 여",
  "Taebaek": "장태백",
  "Geunseok": "근석",
  "MBTI ET (M)": "MBTI ET 남",
  "Taeji": "태지",
  "Geunwoo": "근우",
  "MBTI IF (F)": "MBTI IF 여",
  "Taejoong": "태중",
  "Geunyeong": "근영",
  "MBTI IF (M)": "MBTI IF 남",
  "Taemin": "태민",
  "Ggami": "까미",
  "MBTI IT (F)": "MBTI IT 여",
  "Taesub": "태섭",
  "Ggomi": "꼬미",
  "MBTI IT (M)": "MBTI IT 남",
  "Taewoo": "태우",
  "Glenda": "글렌다",
  "MC Kong": "MC콩",
  "Teal": "틸",
  "Goat Kim": "김고트",
  "MC TypeCast": "MC 타캐",
  "Tessa": "테사",
  "Gongchul": "공철",
  "Mia": "미아",
  "Tian": "티안",
  "Gowoon": "고운",
  "Michael": "마이클",
  "Tim": "팀",
  "Grace": "그레이스",
  "Mija": "오미자",
  "Tina": "티나",
  "Graham": "그레이엄",
  "Mijin": "미진",
  "Toby": "토비",
  "Gunseok": "건석",
  "Mikyung": "미경",
  "Tommy": "토미",
  "Gunwoo": "건우",
  "Millie": "밀리",
  "Tyson": "타이슨",
  "Guri": "구리",
  "Minchae": "민채",
  "UiChan": "의찬이",
  "Gus": "거스",
  "Minji": "민지",
  "Uncle Hank": "행크",
  "Ha Eun": "하은",
  "Minjoon": "민준",
  "Valerie": "밸러리",
  "Haejun": "해준",
  "Minju": "민주",
  "Valkyrie": "발키리",
  "Haerang": "해랑",
  "Minjung": "민정",
  "Vanessa": "바네사",
  "Hailey": "헤일리",
  "Minsang": "민상",
  "Verna": "베르나",
  "Hajun": "하준",
  "Minsu": "민수",
  "Victoria": "빅토리아",
  "Hakchul": "학철",
  "Mio": "미오",
  "Viktor": "빅토르",
  "Hamchu": "햄쮸",
  "Miran Choi": "최미란",
  "Vincent": "빈센트",
  "Han Taesung Caster": "한태성 캐스터",
  "Mirine": "미리내",
  "Vivien": "비비안",
  "Hana": "하나",
  "Miseon": "미선",
  "Wade": "웨이드",
  "Hangyeol": "한결",
  "Miso": "미소",
  "Walter": "월터",
  "Hanjun": "한준",
  "Mister Gop": "미스터 갑",
  "Wangkwon": "왕권",
  "Hanna": "한나",
  "Monggun": "몽군",
  "Weather Reporter Sky": "하늘 캐스터",
  "Hans": "한스",
  "Moonjung": "문정",
  "West": "웨스트",
  "Hansol": "한솔",
  "Mooyeol": "무열",
  "Wonho": "원호",
  "Hanyoung": "한영",
  "Morgan": "모건",
  "Wonkyung": "원경",
  "Harin": "하린",
  "Moru": "머루",
  "Wonwoo": "원우",
  "Harper": "하퍼",
  "Mrs. Claus": "미세스 클로스",
  "Wooju": "우주",
  "Hayul": "하율",
  "Munseok": "문석",
  "Woosung": "우성",
  "Heejoon": "희준",
  "Munsu": "문수",
  "Xavier": "자비에르",
  "Helena": "헬레나",
  "Myeonghee": "명희",
  "Yeeun": "예은",
  "Henry": "헨리",
  "Myungil": "명일",
  "Yejin": "예진",
  "Homun Sim": "심호문",
  "Myungjoo": "명주",
  "Yejoon": "예준",
  "Hoon": "훈",
  "Naeun": "나은",
  "YeLin": "예린",
  "Hosik": "호식",
  "Najin": "나진",
  "Yena": "예나",
  "Hosun": "호선",
  "Namjoon": "남준",
  "Yeonah": "연아",
  "Hoyoung": "호영",
  "Nana": "나나",
  "Yeonggeol": "영걸",
  "Hugh": "휴",
  "Nari": "개나리",
  "Yeonhwa": "연화",
  "Hwimin": "휘민",
  "Nathan": "네이선",
  "Yeonja": "연자",
  "Hyejung": "혜정",
  "Neel": "닐",
  "Yeonsuh": "연서",
  "Hyelee": "혜리",
  "Neoguard": "네오가드",
  "Yeonwoo": "연우",
  "Hyemin": "혜민",
  "News anchor Jinsub": "송진섭 앵커",
  "Yeseul": "예슬",
  "Hyena": "혜나",
  "Newscaster John": "존 앵커",
  "Yongsik": "용식이",
  "Hyeongjin": "형진",
  "Nia": "니아",
  "Yoonseo": "윤서",
  "Hyera": "혜라",
  "Noa": "노아",
  "Yoonsung": "윤성",
  "Hyesu": "홈쇼핑 혜수",
  "Noel": "노엘",
  "Younggil": "영길",
  "Hyewon": "혜원",
  "Noeul": "노을",
  "Younghee": "영희",
  "Hyun": "현",
  "Norah": "노라",
  "Younghwan": "영환",
  "Hyunji": "현지",
  "Nova": "노바",
  "Youngji": "영지",
  "Hyunjin": "현진",
  "Old radio": "레디오",
  "Youngkyu": "영규",
  "Hyunju": "현주",
  "Oliver": "올리버",
  "Youngmok": "영목",
  "Hyunkyung": "현경",
  "Olivia": "올리비아",
  "Yubin": "유빈",
  "Hyunmin": "현민",
  "Oscar": "오스카",
  "Yujin": "유진",
  "Hyunseung": "현승",
  "Owen": "오언",
  "Yumi": "유미",
  "HyunWoo": "현우",
  "P-0150N": "포이즌",
  "Yumin": "유민",
  "Ian": "이안",
  "Pacang": "파캉",
  "Yunbin": "윤빈",
  "Icarus": "이카루스",
  "Paige": "페이지",
  "Yunjeong": "윤정",
  "Igyeom": "이겸",
  "Pangpang": "팡팡",
  "Yura": "유라",
  "Ijun": "이준",
  "Patricia": "패트리샤",
  "Yuri": "유리",
  "Ilho": "일호",
  "Patrick": "패트릭",
  "Yuseong": "유성",
  "Ina": "이나",
  "Peter": "피터",
  "Zoey": "조이",
  "Inhwa": "인화",
  "Philip": "필립",
  "Sanghyun": "상현",
  "Seohyeon": "서현",
  "Juwan": "주완",
  "Jungsook": "정숙",
  "Silas": "실라스",
  "Eoguri": "억울이",
  "Eogwool": "억울이",
  "Mongsil": "몽실",
  "Booqoo": "부쿠",
  "Uwonni": "우니",
  "Woony": "우니"
}

export function typecastKoreanName(englishName: string): string {
  const key = englishName.trim()
  if (!key) return key
  if (TYPECAST_VOICE_NAME_KO[key]) return TYPECAST_VOICE_NAME_KO[key]
  const lower = key.toLowerCase()
  for (const [en, ko] of Object.entries(TYPECAST_VOICE_NAME_KO)) {
    if (en.toLowerCase() === lower) return ko
  }
  return key
}
