import type { ThumbnailProTemplate } from './types'
import { loadCustomTemplates } from './customTemplateStorage'

import { DEFAULT_THUMBNAIL_FONT_STACK, bundledFontStack } from '@/lib/longform-v2/thumbnail-bridge/bundledFonts'

const SERIF_FONT = bundledFontStack('Nanum Barun Gothic')
const SANS_HEAVY = DEFAULT_THUMBNAIL_FONT_STACK

/** 프로 썸네일 템플릿 카탈로그 — `public/thumbnail-templates/` 미리보기 */
export const THUMBNAIL_PRO_TEMPLATES: readonly ThumbnailProTemplate[] = [
  {
    id: 'historical_hook_right',
    label: '템플릿1',
    description: '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 좌측 3단 문구.',
    tags: ['3단', '좌측'],
    previewImageUrl: '/thumbnail-templates/historical-hook-right/preview.png',
    previewCss:
      'linear-gradient(135deg, #1c1917 0%, #44403c 40%, #78716c 70%, #0c0a09 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    textSlots: [
      {
        slotKey: 'hook',
        label: '상단 훅 (검은 박스·기울임)',
        samplePreviewText: '첫번째 문장',
        maxCharacters: 14,
        xn: 0.055,
        yn: 0.69,
        fontSize: 42,
        rotationDeg: -12,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 0,
        textAlign: 'left',
        fontFamily: SERIF_FONT,
        zIndex: 22,
        boxBackground: true,
        boxBackgroundColor: 'rgba(0,0,0,0.94)',
        boxPaddingX: 16,
        boxPaddingY: 8,
        boxRadius: 2,
      },
      {
        slotKey: 'highlight',
        label: '강조 문구 (노랑·수평)',
        samplePreviewText: '두번째 문장',
        maxCharacters: 16,
        xn: 0.055,
        yn: 0.7,
        fontSize: 54,
        rotationDeg: 0,
        fill: '#fde047',
        stroke: '#000000',
        strokeWidth: 6,
        textAlign: 'left',
        fontFamily: SERIF_FONT,
        zIndex: 21,
      },
      {
        slotKey: 'main_title',
        label: '메인 타이틀 (대형·수평)',
        samplePreviewText: '세번째문장',
        maxCharacters: 12,
        xn: 0.055,
        yn: 0.75,
        fontSize: 92,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 20,
      },
    ],
  },
  {
    id: 'cosmic_dual_bottom',
    label: '템플릿2',
    description: '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 좌하 2단 문구.',
    tags: ['2단', '좌하'],
    previewImageUrl: '/thumbnail-templates/cosmic-dual-bottom/preview.png',
    previewCss:
      'linear-gradient(135deg, #0f172a 0%, #1e1b4b 35%, #7c2d12 70%, #020617 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    textSlots: [
      {
        slotKey: 'hook',
        label: '상단 문구 (흰색)',
        samplePreviewText: '첫번째 문구',
        maxCharacters: 14,
        xn: 0.06,
        yn: 0.68,
        fontSize: 76,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 13,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 22,
      },
      {
        slotKey: 'main_title',
        label: '하단 문구 (초록)',
        samplePreviewText: '두번째 문구',
        maxCharacters: 14,
        xn: 0.06,
        yn: 0.8,
        fontSize: 92,
        rotationDeg: 0,
        fill: '#4ade80',
        stroke: '#000000',
        strokeWidth: 15,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 21,
      },
    ],
  },
  {
    id: 'milkyway_center_bottom',
    label: '템플릿3',
    description: '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 하단 중앙 2단 문구.',
    tags: ['2단', '중앙'],
    previewImageUrl: '/thumbnail-templates/milkyway-center-bottom/preview.png',
    previewCss:
      'linear-gradient(180deg, #0c0a09 0%, #1e293b 40%, #312e81 70%, #020617 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    textSlots: [
      {
        slotKey: 'hook',
        label: '상단 문구 (노랑)',
        samplePreviewText: '첫번째 문구',
        maxCharacters: 14,
        xn: 0.5,
        yn: 0.64,
        xnAnchor: 'center',
        ynAnchor: 'center',
        fontSize: 82,
        rotationDeg: 0,
        fill: '#fde047',
        stroke: '#000000',
        strokeWidth: 14,
        textAlign: 'center',
        fontFamily: SANS_HEAVY,
        zIndex: 22,
      },
      {
        slotKey: 'main_title',
        label: '하단 문구 (시안)',
        samplePreviewText: '두번째 문구',
        maxCharacters: 14,
        xn: 0.5,
        yn: 0.78,
        xnAnchor: 'center',
        ynAnchor: 'center',
        fontSize: 82,
        rotationDeg: 0,
        fill: '#22d3ee',
        stroke: '#000000',
        strokeWidth: 14,
        textAlign: 'center',
        fontFamily: SANS_HEAVY,
        zIndex: 21,
      },
    ],
  },
  {
    id: 'landscape_four_left',
    label: '템플릿4',
    description: '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 좌측 4단 문구.',
    tags: ['4단', '좌측'],
    previewImageUrl: '/thumbnail-templates/landscape-four-left/preview.png',
    previewCss:
      'linear-gradient(135deg, #38bdf8 0%, #4ade80 45%, #a855f7 75%, #0f172a 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    textSlots: [
      {
        slotKey: 'hook',
        label: '1줄 상단 (주황)',
        samplePreviewText: '첫번째 상단 문구',
        maxCharacters: 16,
        xn: 0.05,
        yn: 0.1,
        fontSize: 108,
        rotationDeg: 0,
        fill: '#fb923c',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 24,
      },
      {
        slotKey: 'highlight',
        label: '2줄 (시안)',
        samplePreviewText: '두번째 문구',
        maxCharacters: 14,
        xn: 0.05,
        yn: 0.26,
        fontSize: 108,
        rotationDeg: 0,
        fill: '#22d3ee',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 23,
      },
      {
        slotKey: 'sub',
        label: '3줄 (흰색)',
        samplePreviewText: '세번째 문구',
        maxCharacters: 14,
        xn: 0.05,
        yn: 0.44,
        fontSize: 108,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 22,
      },
      {
        slotKey: 'main_title',
        label: '4줄 하단 (노랑)',
        samplePreviewText: '네번째 문구',
        maxCharacters: 14,
        xn: 0.05,
        yn: 0.62,
        fontSize: 108,
        rotationDeg: 0,
        fill: '#fde047',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 21,
      },
    ],
  },
  {
    id: 'astronaut_sparks_right',
    label: '템플릿5',
    description: '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 좌측 3단 문구.',
    tags: ['3단', '좌측'],
    previewImageUrl: '/thumbnail-templates/astronaut-sparks-right/preview.png',
    previewCss:
      'linear-gradient(135deg, #020617 0%, #1e3a5f 40%, #ea580c 65%, #0f172a 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    textSlots: [
      {
        slotKey: 'hook',
        label: '상단 훅 (초록)',
        samplePreviewText: '첫번째상단문구',
        maxCharacters: 14,
        xn: 0.06,
        yn: 0.1,
        fontSize: 44,
        rotationDeg: 0,
        fill: '#4ade80',
        stroke: '#000000',
        strokeWidth: 10,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 23,
      },
      {
        slotKey: 'highlight',
        label: '하단 2줄 (흰색)',
        samplePreviewText: '두번째 문구',
        maxCharacters: 14,
        xn: 0.06,
        yn: 0.72,
        fontSize: 72,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 22,
      },
      {
        slotKey: 'main_title',
        label: '하단 메인 (빨강)',
        samplePreviewText: '세번째 문구',
        maxCharacters: 14,
        xn: 0.06,
        yn: 0.86,
        fontSize: 72,
        rotationDeg: 0,
        fill: '#ef4444',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 21,
      },
    ],
  },
  {
    id: 'scifi_red_frame_left',
    label: '템플릿6',
    description:
      '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 좌하 3단 문구 + 빨간 테두리.',
    tags: ['3단', '테두리'],
    previewImageUrl: '/thumbnail-templates/scifi-red-frame-left/preview.png',
    previewCss:
      'linear-gradient(135deg, #450a0a 0%, #1e1b4b 45%, #312e81 70%, #020617 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    exportFrame: { color: '#dc2626', width: 28, radius: 0 },
    textSlots: [
      {
        slotKey: 'hook',
        label: '상단 문구 (초록·소)',
        samplePreviewText: '상단문구',
        maxCharacters: 12,
        xn: 0.08,
        yn: 0.54,
        fontSize: 40,
        rotationDeg: 0,
        fill: '#4ade80',
        stroke: '#000000',
        strokeWidth: 8,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 23,
      },
      {
        slotKey: 'highlight',
        label: '강조 (노랑·대형)',
        samplePreviewText: '첫번째 문구',
        maxCharacters: 14,
        xn: 0.08,
        yn: 0.66,
        fontSize: 76,
        rotationDeg: 0,
        fill: '#fde047',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 22,
      },
      {
        slotKey: 'main_title',
        label: '하단 (흰색·대형)',
        samplePreviewText: '두번째 문구',
        maxCharacters: 14,
        xn: 0.08,
        yn: 0.8,
        fontSize: 76,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 21,
      },
    ],
  },
  {
    id: 'sejong_dual_bar_left',
    label: '템플릿7',
    description:
      '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 좌하 2단 박스 문구(빨강·검정 바).',
    tags: ['2단', '좌하', '박스'],
    previewImageUrl: '/thumbnail-templates/sejong-dual-bar-left/preview.png',
    previewCss:
      'linear-gradient(135deg, #fce7f3 0%, #a8a29e 35%, #78716c 55%, #1c1917 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    textSlots: [
      {
        slotKey: 'hook',
        label: '상단 문구 (빨간 바)',
        samplePreviewText: '첫번째문구',
        maxCharacters: 14,
        xn: 0.06,
        yn: 0.655,
        ynAnchor: 'center',
        fontSize: 58,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 0,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 22,
        boxBackground: true,
        boxBackgroundColor: '#dc2626',
        boxPaddingX: 20,
        boxPaddingY: 16,
        boxRadius: 0,
      },
      {
        slotKey: 'main_title',
        label: '하단 문구 (검정 바)',
        samplePreviewText: '두번째문구',
        maxCharacters: 14,
        xn: 0.06,
        yn: 0.805,
        ynAnchor: 'center',
        fontSize: 58,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 0,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 21,
        boxBackground: true,
        boxBackgroundColor: 'rgba(0,0,0,0.96)',
        boxPaddingX: 20,
        boxPaddingY: 16,
        boxRadius: 0,
      },
    ],
  },
  {
    id: 'joseon_hook_dual_left',
    label: '템플릿8',
    description:
      '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 좌상 훅 박스 + 좌하 2단 문구.',
    tags: ['3단', '좌측', '훅'],
    previewImageUrl: '/thumbnail-templates/joseon-hook-dual-left/preview.png',
    previewCss:
      'linear-gradient(135deg, #1c1917 0%, #57534e 40%, #78716c 65%, #0c0a09 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    textSlots: [
      {
        slotKey: 'hook',
        label: '후킹 문구 (흰 박스·기울임)',
        samplePreviewText: '후킹 문구',
        maxCharacters: 12,
        xn: 0.06,
        yn: 0.1,
        fontSize: 38,
        rotationDeg: -8,
        fill: '#0c0a09',
        stroke: '#000000',
        strokeWidth: 0,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 23,
        boxBackground: true,
        boxBackgroundColor: '#ffffff',
        boxPaddingX: 14,
        boxPaddingY: 8,
        boxRadius: 2,
      },
      {
        slotKey: 'highlight',
        label: '첫번째 문구 (흰색·대형)',
        samplePreviewText: '첫번째문구',
        maxCharacters: 14,
        xn: 0.05,
        yn: 0.72,
        fontSize: 115,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 10,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 22,
      },
      {
        slotKey: 'main_title',
        label: '두번째 문구 (시안·대형)',
        samplePreviewText: '두번째문구',
        maxCharacters: 14,
        xn: 0.05,
        yn: 0.84,
        fontSize: 115,
        rotationDeg: 0,
        fill: '#22d3ee',
        stroke: '#000000',
        strokeWidth: 10,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 21,
      },
    ],
  },
  {
    id: 'battle_news_bottom_center',
    label: '템플릿9',
    description:
      '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 좌상 기사형 + 하단 중앙 2~3단.',
    tags: ['4단', '중앙', '기사'],
    previewImageUrl: '/thumbnail-templates/battle-news-bottom-center/preview.png',
    previewCss:
      'linear-gradient(180deg, #0c0a09 0%, #44403c 45%, #78716c 70%, #1c1917 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    textSlots: [
      {
        slotKey: 'hook',
        label: '상단 문구 (라임)',
        samplePreviewText: '상단문구',
        maxCharacters: 12,
        xn: 0.05,
        yn: 0.08,
        fontSize: 44,
        rotationDeg: 0,
        fill: '#a3e635',
        stroke: '#000000',
        strokeWidth: 10,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 24,
      },
      {
        slotKey: 'sub',
        label: '상단 기사 문구 (흰 박스)',
        samplePreviewText: '상단 기사 문구1',
        maxCharacters: 16,
        xn: 0.05,
        yn: 0.18,
        fontSize: 34,
        rotationDeg: 0,
        fill: '#0c0a09',
        stroke: '#000000',
        strokeWidth: 0,
        textAlign: 'left',
        fontFamily: SERIF_FONT,
        zIndex: 23,
        boxBackground: true,
        boxBackgroundColor: '#ffffff',
        boxPaddingX: 12,
        boxPaddingY: 8,
        boxRadius: 0,
      },
      {
        slotKey: 'highlight',
        label: '첫번째 문구 (흰색·중앙)',
        samplePreviewText: '첫번째문구',
        maxCharacters: 14,
        xn: 0.5,
        yn: 0.62,
        xnAnchor: 'center',
        ynAnchor: 'center',
        fontSize: 58,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'center',
        fontFamily: SANS_HEAVY,
        zIndex: 22,
      },
      {
        slotKey: 'main_title',
        label: '두번째 문구 (라임·핵심)',
        samplePreviewText: '두번째 문구',
        maxCharacters: 14,
        xn: 0.28,
        yn: 0.76,
        xnAnchor: 'center',
        ynAnchor: 'center',
        fontSize: 68,
        rotationDeg: 0,
        fill: '#a3e635',
        stroke: '#000000',
        strokeWidth: 14,
        textAlign: 'center',
        fontFamily: SANS_HEAVY,
        zIndex: 21,
      },
      {
        slotKey: 'accent',
        label: '핵심 문구 (주황)',
        samplePreviewText: '핵심문구',
        maxCharacters: 10,
        xn: 0.72,
        yn: 0.76,
        xnAnchor: 'center',
        ynAnchor: 'center',
        fontSize: 68,
        rotationDeg: 0,
        fill: '#fb923c',
        stroke: '#000000',
        strokeWidth: 14,
        textAlign: 'center',
        fontFamily: SANS_HEAVY,
        zIndex: 20,
      },
    ],
  },
  {
    id: 'planet_italic_dual_left',
    label: '템플릿10',
    description:
      '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 좌하 2단 기울임 문구.',
    tags: ['2단', '좌하'],
    previewImageUrl: '/thumbnail-templates/planet-italic-dual-left/preview.png',
    previewCss:
      'linear-gradient(135deg, #0f172a 0%, #1e1b4b 35%, #312e81 60%, #020617 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    textSlots: [
      {
        slotKey: 'hook',
        label: '첫번째 문구 (흰색·기울임)',
        samplePreviewText: '지구만 딱?',
        maxCharacters: 14,
        xn: 0.06,
        yn: 0.68,
        fontSize: 100,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 22,
      },
      {
        slotKey: 'main_title',
        label: '두번째 문구 (노랑·기울임)',
        samplePreviewText: '두번째 문구',
        maxCharacters: 14,
        xn: 0.06,
        yn: 0.82,
        fontSize: 100,
        rotationDeg: 0,
        fill: '#fde047',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 21,
      },
    ],
  },
  {
    id: 'cartoon_dual_top_left',
    label: '템플릿11',
    description:
      '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 좌상 2단 문구.',
    tags: ['2단', '좌상'],
    previewImageUrl: '/thumbnail-templates/cartoon-dual-top-left/preview.png',
    previewCss:
      'linear-gradient(135deg, #0d9488 0%, #4ade80 35%, #fde047 65%, #38bdf8 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    textSlots: [
      {
        slotKey: 'hook',
        label: '첫번째 문구 (민트)',
        samplePreviewText: '골디락스 존?',
        maxCharacters: 14,
        xn: 0.05,
        yn: 0.1,
        fontSize: 106,
        rotationDeg: 0,
        fill: '#6ee7b7',
        stroke: '#0c0a09',
        strokeWidth: 10,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 22,
      },
      {
        slotKey: 'main_title',
        label: '두번째 문구 (흰색)',
        samplePreviewText: '제2의 지구 찾았다',
        maxCharacters: 14,
        xn: 0.05,
        yn: 0.24,
        fontSize: 106,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#0c0a09',
        strokeWidth: 10,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 21,
      },
    ],
  },
  {
    id: 'classical_red_frame_left',
    label: '템플릿12',
    description:
      '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 좌하 1단 + 빨간 테두리.',
    tags: ['1단', '테두리', '좌하'],
    previewImageUrl: '/thumbnail-templates/classical-red-frame-left/preview.png',
    previewCss:
      'linear-gradient(135deg, #450a0a 0%, #78716c 40%, #d6d3d1 70%, #1c1917 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    exportFrame: { color: '#dc2626', width: 24, radius: 0 },
    textSlots: [
      {
        slotKey: 'main_title',
        label: '첫번째 문구 (흰색·좌하)',
        samplePreviewText: '첫번째 문구',
        maxCharacters: 16,
        xn: 0.06,
        yn: 0.82,
        fontSize: 114,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 10,
        textAlign: 'left',
        fontFamily: SANS_HEAVY,
        zIndex: 21,
      },
    ],
  },
  {
    id: 'diplomatic_dual_bottom_center',
    label: '템플릿13',
    description:
      '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 하단 중앙 2단 문구.',
    tags: ['2단', '중앙', '하단'],
    previewImageUrl: '/thumbnail-templates/diplomatic-dual-bottom-center/preview.png',
    previewCss:
      'linear-gradient(180deg, #1c1917 0%, #44403c 50%, #78716c 75%, #0c0a09 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    textSlots: [
      {
        slotKey: 'hook',
        label: '첫번째 문구 (노랑)',
        samplePreviewText: '지구랑 똑같네?',
        maxCharacters: 14,
        xn: 0.5,
        yn: 0.68,
        xnAnchor: 'center',
        ynAnchor: 'center',
        fontSize: 110,
        rotationDeg: 0,
        fill: '#fde047',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'center',
        fontFamily: SANS_HEAVY,
        zIndex: 22,
      },
      {
        slotKey: 'main_title',
        label: '두번째 문구 (흰색)',
        samplePreviewText: '골디락스 존, 제2의 지구',
        maxCharacters: 18,
        xn: 0.5,
        yn: 0.82,
        xnAnchor: 'center',
        ynAnchor: 'center',
        fontSize: 110,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'center',
        fontFamily: SANS_HEAVY,
        zIndex: 21,
      },
    ],
  },
  {
    id: 'landscape_triple_center',
    label: '템플릿14',
    description:
      '미리보기는 글자 배치 샘플입니다. 배경·인물은 주제·대본으로 생성됩니다. 상·중·하 3단 중앙 박스 문구.',
    tags: ['3단', '중앙', '박스'],
    previewImageUrl: '/thumbnail-templates/landscape-triple-center/preview.png',
    previewCss:
      'linear-gradient(180deg, #38bdf8 0%, #4ade80 40%, #86efac 65%, #0ea5e9 100%)',
    backgroundPromptTemplate:
      'YouTube thumbnail background illustrating VIDEO TOPIC only (not template sample photo). Cinematic 16:9, no text, no letters. Topic: {topic}. Script mood: {scriptExcerpt}',
    textSlots: [
      {
        slotKey: 'hook',
        label: '핵심 문구 (흰 박스·상단)',
        samplePreviewText: '우주에 이런',
        maxCharacters: 10,
        xn: 0.5,
        yn: 0.12,
        xnAnchor: 'center',
        ynAnchor: 'center',
        fontSize: 40,
        rotationDeg: 0,
        fill: '#0c0a09',
        stroke: '#000000',
        strokeWidth: 0,
        textAlign: 'center',
        fontFamily: SANS_HEAVY,
        zIndex: 23,
        boxBackground: true,
        boxBackgroundColor: '#ffffff',
        boxPaddingX: 18,
        boxPaddingY: 10,
        boxRadius: 10,
      },
      {
        slotKey: 'highlight',
        label: '첫번째 문구 (흰색·중앙)',
        samplePreviewText: '숨겨진 비밀이?',
        maxCharacters: 14,
        xn: 0.5,
        yn: 0.48,
        xnAnchor: 'center',
        ynAnchor: 'center',
        fontSize: 72,
        rotationDeg: 0,
        fill: '#ffffff',
        stroke: '#000000',
        strokeWidth: 12,
        textAlign: 'center',
        fontFamily: SANS_HEAVY,
        zIndex: 22,
      },
      {
        slotKey: 'main_title',
        label: '두번째 문구 (초록·검정 박스)',
        samplePreviewText: '제2의 지구, 찾았다!',
        maxCharacters: 18,
        xn: 0.5,
        yn: 0.78,
        xnAnchor: 'center',
        ynAnchor: 'center',
        fontSize: 76,
        rotationDeg: 0,
        fill: '#4ade80',
        stroke: '#000000',
        strokeWidth: 0,
        textAlign: 'center',
        fontFamily: SANS_HEAVY,
        zIndex: 21,
        boxBackground: true,
        boxBackgroundColor: 'rgba(15, 20, 25, 0.94)',
        boxWidthPx: 680,
        boxPaddingX: 24,
        boxPaddingY: 18,
        boxRadius: 14,
      },
    ],
  },
] as const

export type ThumbnailProTemplateId = (typeof THUMBNAIL_PRO_TEMPLATES)[number]['id']

const BY_ID = Object.fromEntries(THUMBNAIL_PRO_TEMPLATES.map((t) => [t.id, t])) as Record<
  string,
  ThumbnailProTemplate
>

export function getProTemplate(id: string): ThumbnailProTemplate | undefined {
  if (id === 'study_hook_right') return BY_ID.historical_hook_right
  const builtin = BY_ID[id]
  if (builtin) return builtin
  return loadCustomTemplates().find((t) => t.id === id)
}

/** 기본 + 커스텀 템플릿 전체 목록 */
export function listAllProTemplates(): ThumbnailProTemplate[] {
  return [...THUMBNAIL_PRO_TEMPLATES, ...loadCustomTemplates()]
}

export function listProTemplateIds(): string[] {
  return listAllProTemplates().map((t) => t.id)
}

export const DEFAULT_PRO_TEMPLATE_ID: ThumbnailProTemplateId = 'historical_hook_right'
